
























# Generated by Django 4.0.5 on 2022-06-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereço', models.CharField(max_length=200)),
                ('cep', models.IntegerField()),
                ('num', models.IntegerField()),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=30)),
                ('descrição', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ENDEREÇOS',
            },
        ),
    ]
