# Generated by Django 4.0.5 on 2022-06-25 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='endereço',
            new_name='end',
        ),
    ]
